### ISSUE TITLE
New update broke some functions

### ISSUE THREAD

**Issue by erwin1234777** [nhentai-dev/API#2]
this is the error logged

(node:8056) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at Object.details (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\src\parse.js:18:53)
    at parseDetailsHTML (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\index.js:14:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nHentaiAPI.g (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\index.js:50:29)

**Comment by erwin1234777** [comment]
just adding another comment to mention its not the only function broken

(node:8056) UnhandledPromiseRejectionWarning: Error: Request failed with status code 502
    at createError (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\node_modules\axios\lib\core\createError.js:16:15)
    at settle (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (c:\Users\DELL\Desktop\NotABot\node_modules\nhentai-api-js\node_modules\axios\lib\adapters\http.js:202:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

basically a lot of it broke

**Comment by Tsuk1ko** [comment]
@erwin1234777 Recommend to use [nhentai-api](https://www.npmjs.com/package/nhentai-api) instead.

My api project works by parsing html content. If nHentai updates its html structure, these errors will occur.

I currently don’t want to continue to maintain it.

> It was developed because [official API has been suspended indefinitely](https://twitter.com/fuckmaou/status/1084550608097603585).
>
> But now you don't need it anymore, [official API is re-enabled](https://twitter.com/fuckmaou/status/1113868849500303363).
